package com.echallenge.model;

public enum Theme {
PRODUCTIVITE, QUALITE_FIABILITE, TECHNICITE, CONCEPTION,
AVANT_VENTE, GESTION_DE_PROJET, GESTION_DE_RELATION_CLIENT,
GESTION_DES_EQUIPES, POLYVALENCE
}
